-- Categories
insert into categories (id, name, slug, icon, description, image, col_span) values
('bano', 'Baño', 'bano', 'bathtub', 'Higiene y accesorios', 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80', 'full'),
('uso-personal', 'Uso Personal', 'uso-personal', 'clean_hands', 'Higiene personal', 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&q=80', null),
('cocina', 'Cocina', 'cocina', 'kitchen', 'Limpieza de cocina', 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80', null),
('casa', 'Casa', 'casa', 'home', 'Limpieza del hogar', 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=400&q=80', null),
('ropa', 'Ropa', 'ropa', 'laundry', 'Lavado de ropa', 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400&q=80', null),
('etc', 'Etc', 'etc', 'more_horiz', 'Lámparas y termos', '', null)
on conflict (id) do nothing;

-- Products
insert into products (id, slug, name, brand, category, unit, price, compare_at_price, description, in_stock, is_featured, image, rating, reviews) values
('1','odex-bano-doypack-450ml','Odex Limpieza Baño Doy Pack','Odex','bano','450ml',1408,null,'Limpiador de baño fórmula concentrada en envase Doy Pack.',true,true,'',4.8,42),
('2','odex-vidrio-doypack-450ml','Odex Vidrio Doy Pack','Odex','bano','450ml',1408,null,'Limpiador de vidrios y superficies brillantes.',true,false,'',null,null),
('3','escobilla-bano-base-silva','Escobilla de Baño con Base','Silva','bano','unidad',2983,null,'Escobilla de baño con base incluida.',true,false,'',null,null),
('4','esponja-vegetal','Esponja Vegetal','Virulana','bano','unidad',1942,null,'Esponja natural vegetal de alta durabilidad.',true,false,'',null,null),
('5','sopapa-destapadora-silva','Sopapa Destapadora','Silva','bano','unidad',2045,null,'Sopapa de goma para desatascar cañerías.',true,false,'',null,null),
('6','colgate-original-70g','Pasta Dientes Original','Colgate','uso-personal','70g',2438,null,'Pasta dental original Colgate con flúor.',true,true,'',4.9,120),
('7','colgate-luminous-white-70g','Pasta Dientes Luminous White','Colgate','uso-personal','70g',4973,null,'Blanqueamiento avanzado y protección de esmalte.',true,false,'',null,null),
('8','colgate-triple-beneficio-70g','Pasta Dientes Triple Beneficio','Colgate','uso-personal','70g',2792,null,'Triple acción: blanqueamiento, anticaries y frescura.',true,false,'',null,null),
('9','palmolibre-frambuesa','Jabón Palmolibre Frambuesa','Palmolibre','uso-personal','60g',730,null,'Barra de jabón hidratante fragancia frambuesa.',true,false,'',null,null),
('10','palmolibre-aloe-vera','Jabón Palmolibre Aloe Vera','Palmolibre','uso-personal','60g',730,null,'Barra de jabón con aloe vera para piel sensible.',true,false,'',null,null),
('11','palmolibre-cacao','Jabón Palmolibre Cacao','Palmolibre','uso-personal','60g',730,null,'Barra de jabón hidratante con extracto de cacao.',true,false,'',null,null),
('12','toallas-pocket-normal-alas-x8','Toallas Pocket Normal con Alas','Doncella','uso-personal','x8',714,null,'Toallas higiénicas con alas para mayor seguridad.',true,false,'',null,null),
('13','toallas-pocket-sin-alas-x8','Toallas Pocket Normal sin Alas','Doncella','uso-personal','x8',714,null,'Toallas higiénicas sin alas.',true,false,'',null,null),
('14','toallas-pocket-nocturnas-x8','Toallas Pocket Nocturnas','Doncella','uso-personal','x8',1221,null,'Toallas nocturnas de mayor protección.',true,false,'',null,null),
('15','toallas-pocket-nocturnas-x16','Toallas Pocket Nocturnas','Doncella','uso-personal','x16',2392,null,'Pack x16 toallas nocturnas.',true,false,'',null,null),
('16','protector-diario-anatomico-x20','Protector Diario Anatómico','Doncella','uso-personal','x20',811,null,'Protectores diarios anatómicos ultra finos.',true,false,'',null,null),
('17','toallas-pocket-tanga-x8','Toallas Pocket Tanga con Alas','Doncella','uso-personal','x8',842,null,'Toallas para tanga con alas adhesivas.',true,false,'',null,null),
('18','plax-rojo-250ml','Plax Rojo','Colgate','uso-personal','250ml',4430,null,'Enjuague bucal Plax fórmula roja anti bacterias.',true,false,'',null,null),
('19','plax-menta-suave-250ml','Plax Menta Suave','Colgate','uso-personal','250ml',4430,null,'Enjuague bucal Plax menta suave.',true,false,'',null,null),
('20','cepillo-extra-clean-mediano-2pack','Cepillo Extra Clean Mediano','Colgate','uso-personal','2 pack',3900,null,'Pack 2 cepillos dental extra clean cerdas medianas.',true,false,'',null,null),
('21','cepillo-max-white-mediano-2x1','Cepillo Max White Mediano','Colgate','uso-personal','2x1',5417,null,'Cepillo blanqueador Max White pack 2x1.',true,false,'',null,null),
('22','virulana-pano-twist','Paño Twist','Virulana','cocina','unidad',1566,null,'Paño multiuso torsionado extra absorbente.',true,true,'',null,null),
('23','virulana-pano-esponja','Paño Esponja','Virulana','cocina','unidad',1240,null,'Paño esponja doble función: lavar y secar.',true,false,'',null,null),
('24','virulana-trapo-microfibra-piso','Trapo Microfibra Piso','Virulana','cocina','unidad',6232,null,'Trapo de piso microfibra ultra absorbente.',true,false,'',null,null),
('25','virulana-expert-microfibra-escurridor','Expert Paño Microfibra Piso Escurridor','Virulana','cocina','unidad',6232,null,'Paño microfibra con escurridor incluido.',true,false,'',null,null),
('26','guante-mapa-s','Guante Mapa S','Virulana','cocina','talle S',2717,null,'Guante de limpieza resistente.',true,false,'',null,null),
('27','guante-mapa-m','Guante Mapa M','Virulana','cocina','talle M',2717,null,'Guante de limpieza resistente.',true,false,'',null,null),
('28','guante-mapa-l','Guante Mapa L','Virulana','cocina','talle L',2717,null,'Guante de limpieza resistente.',true,false,'',null,null),
('29','guante-plumita-s','Guante Plumita S','Virulana','cocina','talle S',1864,null,'Guante liviano de látex.',true,false,'',null,null),
('30','guante-plumita-m','Guante Plumita M','Virulana','cocina','talle M',1864,null,'Guante liviano de látex.',true,false,'',null,null),
('31','esponja-antigrasa','Esponja Antigrasa','Virulana','cocina','unidad',742,null,'Esponja doble faz antigrasa.',true,true,'',null,null),
('32','esponja-multiuso','Esponja Multiuso','Virulana','cocina','unidad',541,null,'Esponja multiuso suave.',true,false,'',null,null),
('33','esponja-cuadraditos','Esponja Cuadraditos','Virulana','cocina','unidad',592,null,'Pack esponjas cuadradas.',true,false,'',null,null),
('34','esponja-lisa','Esponja Lisa','Virulana','cocina','unidad',503,null,'Esponja lisa suave para superficies delicadas.',true,false,'',null,null),
('35','virulana-inoxi','Inoxi','Virulana','cocina','unidad',623,null,'Virulana inoxidable para ollas y sartenes.',true,false,'',null,null),
('36','virulana-rollito-x6','Rollito Virulana','Virulana','cocina','x6',1072,null,'Pack 6 rollitos de acero inoxidable.',true,false,'',null,null),
('37','virulana-rollito-x10','Rollito Virulana','Virulana','cocina','x10',1654,null,'Pack 10 rollitos de acero inoxidable.',true,false,'',null,null),
('38','odex-antigrasa-doypack-450ml','Antigrasa Doy Pack','Odex','cocina','450ml',1480,null,'Desengrasante concentrado en Doy Pack.',true,false,'',null,null),
('39','odex-gatillo-antigrasa-500ml','Gatillo Antigrasa','Odex','cocina','500ml',2774,null,'Desengrasante con gatillo listo para usar.',true,false,'',null,null),
('40','virulana-cabo-metalico','Virulana Cabo Metálico','Virulana','cocina','unidad',2834,null,'Virulana con cabo metálico resistente.',true,false,'',null,null),
('41','secador-piso-30cm','Secador de Piso 30cm','Virulana','cocina','30cm',3127,null,'Secador de piso con goma resistente.',true,false,'',null,null),
('42','secador-piso-40cm','Secador de Piso 40cm','Virulana','cocina','40cm',3448,null,'Secador de piso ancho de alta cobertura.',true,false,'',null,null),
('43','suiza-pasta-roble-claro-250g','Pasta Natural Roble Claro','Suiza','casa','250g',8200,null,'Pasta para pisos de madera, tono roble claro.',true,true,'',null,null),
('44','suiza-pasta-roble-oscuro-250g','Pasta Natural Roble Oscuro','Suiza','casa','250g',8200,null,'Pasta para pisos de madera, tono roble oscuro.',true,false,'',null,null),
('45','suiza-cera-neutral-425ml','Cera Líquida Neutral','Suiza','casa','425ml',4577,null,'Cera líquida incolora para todo tipo de piso.',true,false,'',null,null),
('46','suiza-cera-roble-claro-425ml','Cera Líquida Roble Claro','Suiza','casa','425ml',4577,null,'Cera líquida tono roble claro.',true,false,'',null,null),
('47','suiza-cera-roble-oscuro-425ml','Cera Líquida Roble Oscuro','Suiza','casa','425ml',4577,null,'Cera líquida tono roble oscuro.',true,false,'',null,null),
('48','suiza-cera-850ml','Cera Líquida 850ml','Suiza','casa','850ml',7486,9500,'Cera líquida formato económico 850ml.',true,false,'',null,null),
('49','suiza-autobrillo-rojo-400ml','Autobrillo Rojo','Suiza','casa','Doy Pack 400ml',3141,null,'Autobrillo líquido para pisos rojos y terracota.',true,false,'',null,null),
('50','suiza-autobrillo-negro-400ml','Autobrillo Negro','Suiza','casa','Doy Pack 400ml',3141,null,'Autobrillo líquido para pisos negros.',true,false,'',null,null),
('51','suiza-autobrillo-incoloro-400ml','Autobrillo Incoloro','Suiza','casa','Doy Pack 400ml',3141,null,'Autobrillo incoloro para todo tipo de piso.',true,false,'',null,null),
('52','suiza-lustra-muebles-neutro','Lustra Muebles Neutro','Suiza','casa','300ml',3393,null,'Lustrador de muebles sin fragancia.',true,false,'',null,null),
('53','suiza-lustra-muebles-lavanda','Lustra Muebles Lavanda','Suiza','casa','300ml',3393,null,'Lustrador de muebles fragancia lavanda.',true,false,'',null,null),
('54','suiza-lustra-muebles-naranja-pimienta','Lustra Muebles Naranja Pimienta','Suiza','casa','300ml',3393,null,'Lustrador de muebles fragancia naranja y pimienta.',true,false,'',null,null),
('55','virulana-escobon-tradicional','Escobillón Tradicional','Virulana','casa','madera',3903,null,'Escobillón mango de madera cerdas resistentes.',true,false,'',null,null),
('56','virulana-escobon-clasico','Escobillón Clásico','Virulana','casa','plástico',4643,null,'Escobillón mango plástico liviano.',true,false,'',null,null),
('57','virulana-balde-escurridor-12l','Balde con Escurridor','Virulana','casa','12L',8123,10000,'Balde 12 litros con escurridor integrado.',true,true,'',null,null),
('58','querubin-polvo-400g','Polvo Lavar Ropa Baja Espumas','Querubín','ropa','400g',1400,null,'Polvo lavante baja espuma ideal para lavarropas.',true,true,'',null,null),
('59','querubin-polvo-800g','Polvo Lavar Ropa Baja Espumas','Querubín','ropa','800g',2801,3500,'Formato económico 800g polvo baja espuma.',true,false,'',null,null),
('60','querubin-suavizante-silvestres-3l','Suavizante Flores Silvestres','Querubín','ropa','3L',8764,null,'Suavizante fragancia flores silvestres 3 litros.',true,false,'',null,null),
('61','querubin-suavizante-estrictas-800ml','Suavizante Flores Estrictas','Querubín','ropa','800ml',2788,null,'Suavizante fragancia flores 800ml.',true,false,'',null,null),
('62','jabon-blanco-300g','Jabón Blanco','Genérico','ropa','300g',2000,null,'Jabón blanco multiuso para ropa.',true,false,'',null,null),
('63','querubin-liquido-3l','Líquido Lavar Ropa','Querubín','ropa','3L',8764,null,'Detergente líquido para ropa 3 litros.',true,false,'',null,null),
('64','querubin-liquido-800ml','Líquido Lavar Ropa','Querubín','ropa','800ml',2548,null,'Detergente líquido para ropa 800ml.',true,false,'',null,null),
('65','bulbo-7w-frio','Bulbo LED Frío 7W','Genérico','etc','7W',866,null,'Lámpara LED luz fría 7 watts.',true,false,'',null,null),
('66','bulbo-7w-calido','Bulbo LED Cálido 7W','Genérico','etc','7W',866,null,'Lámpara LED luz cálida 7 watts.',true,false,'',null,null),
('67','bulbo-9w-frio','Bulbo LED Frío 9W','Genérico','etc','9W',907,null,'Lámpara LED luz fría 9 watts.',true,false,'',null,null),
('68','bulbo-9w-calido','Bulbo LED Cálido 9W','Genérico','etc','9W',907,null,'Lámpara LED luz cálida 9 watts.',true,false,'',null,null),
('69','bulbo-12w-frio','Bulbo LED Frío 12W','Genérico','etc','12W',1081,null,'Lámpara LED luz fría 12 watts.',true,false,'',null,null),
('70','bulbo-12w-calido','Bulbo LED Cálido 12W','Genérico','etc','12W',1081,null,'Lámpara LED luz cálida 12 watts.',true,false,'',null,null),
('71','bulbo-15w-frio','Bulbo LED Frío 15W','Genérico','etc','15W',1316,null,'Lámpara LED luz fría 15 watts.',true,false,'',null,null),
('72','bulbo-15w-calido','Bulbo LED Cálido 15W','Genérico','etc','15W',1316,null,'Lámpara LED luz cálida 15 watts.',true,false,'',null,null),
('73','termo-gris-700ml','Termo Gris','Genérico','etc','700ml',50000,null,'Termo acero inoxidable color gris 700ml.',true,false,'',null,null),
('74','termo-negro-700ml','Termo Negro','Genérico','etc','700ml',50000,null,'Termo acero inoxidable color negro 700ml.',true,false,'',null,null)
on conflict (id) do nothing;
